item { 
	name:'angklung'
	id:1
}
item { 
	name:'badik'
	id:2
}
item { 
	name:'iket_sunda'
	id:3
}
item { 
	name:'kecapi_sunda'
	id:4
}
item { 
	name:'kekarangan'
	id:5
}
item { 
	name:'kujang'
	id:6
}
item { 
	name:'pangsi_sunda'
	id:7
}
item { 
	name:'payung_geulis'
	id:8
}
item { 
	name:'saput_poleng'
	id:9
}
item { 
	name:'sasando'
	id:10
}
item { 
	name:'siger_sunda'
	id:11
}
item { 
	name:'songket'
	id:12
}
item { 
	name:'songkok_bone'
	id:13
}
item { 
	name:'suling'
	id:14
}
item { 
	name:'tanjak_minang'
	id:15
}
item { 
	name:'tau_tau'
	id:16
}
item { 
	name:'tii_langga'
	id:17
}
item { 
	name:'tingkuluak'
	id:18
}
item { 
	name:'tongkonan'
	id:19
}
item { 
	name:'topeng_barong'
	id:20
}
item { 
	name:'wayang_golek'
	id:21
}
item { 
	name:'blangkon'
	id:22
}
item { 
	name:'clurit_madura'
	id:23
}
item { 
	name:'golok_betawi'
	id:24
}
item { 
	name:'joglo'
	id:25
}
item { 
	name:'keris_jawa'
	id:26
}
item { 
	name:'kuluk'
	id:27
}
item { 
	name:'ondel_ondel'
	id:28
}
item { 
	name:'pangsi_betawi'
	id:29
}
item { 
	name:'reog'
	id:30
}
item { 
	name:'surjan'
	id:31
}
item { 
	name:'wayang_kulit'
	id:32
}
item { 
	name:'tali_tali'
	id:33
}
item { 
	name:'sortali'
	id:34
}
item { 
	name:'ampe_ampe'
	id:35
}
item { 
	name:'hoba_hoba'
	id:36
}
item { 
	name:'bolon'
	id:37
}
item { 
	name:'bulang'
	id:38
}
item { 
	name:'gondang'
	id:39
}
item { 
	name:'piso_halasan'
	id:40
}
item { 
	name:'haen'
	id:41
}
item { 
	name:'singkot'
	id:42
}
